INSERT INTO users (id, username, password, email, last_login) VALUES (1, 'user1', '$2b$10$auo83gilgt5', 'user1@example.com', '2026-02-25T19:15:45.166Z');
INSERT INTO users (id, username, password, email, last_login) VALUES (2, 'user2', '$2b$10$nezkjnr3udi', 'user2@example.com', '2026-02-08T19:15:45.169Z');
INSERT INTO users (id, username, password, email, last_login) VALUES (3, 'user3', '$2b$10$vt2dot3cqs', 'user3@example.com', '2026-02-22T19:15:45.169Z');
INSERT INTO users (id, username, password, email, last_login) VALUES (4, 'user4', '$2b$10$kfpzn62ivt8', 'user4@example.com', '2026-02-15T19:15:45.169Z');
INSERT INTO users (id, username, password, email, last_login) VALUES (5, 'user5', '$2b$10$kctb3g1wt7k', 'user5@example.com', '2026-02-26T19:15:45.169Z');
INSERT INTO blog_posts (id, user_id, title, content, cover) VALUES (1, 536, 'Blog Post 1', 'This is the content of blog post 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'https://picsum.photos/800/600?random=1');
INSERT INTO blog_posts (id, user_id, title, content, cover) VALUES (2, 125, 'Blog Post 2', 'This is the content of blog post 2. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'https://picsum.photos/800/600?random=2');
INSERT INTO blog_posts (id, user_id, title, content, cover) VALUES (3, 129, 'Blog Post 3', 'This is the content of blog post 3. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'https://picsum.photos/800/600?random=3');
INSERT INTO blog_posts (id, user_id, title, content, cover) VALUES (4, 299, 'Blog Post 4', 'This is the content of blog post 4. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'https://picsum.photos/800/600?random=4');
INSERT INTO blog_posts (id, user_id, title, content, cover) VALUES (5, 735, 'Blog Post 5', 'This is the content of blog post 5. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'https://picsum.photos/800/600?random=5');
INSERT INTO comments (id, blog_id, user_id, content) VALUES (1, 21, 825, 'This is the content of blog post 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
INSERT INTO comments (id, blog_id, user_id, content) VALUES (2, 831, 667, 'This is the content of blog post 2. Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
INSERT INTO comments (id, blog_id, user_id, content) VALUES (3, 696, 359, 'This is the content of blog post 3. Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
INSERT INTO comments (id, blog_id, user_id, content) VALUES (4, 368, 196, 'This is the content of blog post 4. Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
INSERT INTO comments (id, blog_id, user_id, content) VALUES (5, 878, 947, 'This is the content of blog post 5. Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
INSERT INTO tags (id, name) VALUES (1, 'react');
INSERT INTO tags (id, name) VALUES (2, 'node');
INSERT INTO tags (id, name) VALUES (3, 'database');
INSERT INTO tags (id, name) VALUES (4, 'css');
INSERT INTO tags (id, name) VALUES (5, 'html');
INSERT INTO blog_tag (blog_id, tag_id) VALUES (1, 1);
INSERT INTO blog_tag (blog_id, tag_id) VALUES (2, 2);
INSERT INTO blog_tag (blog_id, tag_id) VALUES (3, 3);
INSERT INTO blog_tag (blog_id, tag_id) VALUES (4, 4);
INSERT INTO blog_tag (blog_id, tag_id) VALUES (5, 5);
